import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import NextAuthProvider from "@/providers/NextAuth";
import { Toaster } from "@/components/ui/toaster";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const news = [
    { contents: "news1", date: "2022-01-01" },
    { contents: "news2", date: "2022-01-02" },
    { contents: "news3", date: "2022-01-03" },
    { contents: "news4", date: "2022-01-04" },
    { contents: "news5", date: "2022-01-05" },
    { contents: "news6", date: "2022-01-06" },
    { contents: "news7", date: "2022-01-07" },
    { contents: "news8", date: "2022-01-08" },
    { contents: "news9", date: "2022-01-09" },
    { contents: "news10", date: "2022-01-10" },
  ];
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <Header />
          {children}
          <Footer news={news} />
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
