import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const session = {
  user: {
    name: "John Doe",
    email: "y220010@mail.ryukoku.ac.jp",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="my-class-name">
        <header style={{ width: "100%", backgroundColor: "#F1F5F9" }}>
          <div className="h-[146px] justify-center items-center flex">
            <div className="h-[146px] pl-6 pr-[25px] pt-[39px] pb-[35px]  justify-center items-center flex">
              <div className="h-[72px] text-red-600 text-3xl font-bold font-['Inter']">
                <Link href="/">
                  龍谷大学<br></br>交流会館予約アプリ
                </Link>
              </div>

              {!session && (
                <div>
                  <Link href="/">home</Link>
                  <Link href="/">Mypage</Link>
                </div>
              )}
            </div>
          </div>
        </header>
        {children}

        <footer className="flex  justify-center  ">
          <div className="flex flex-col items-center justify-center  space-y-4 bg-white ">
            <div className=" font-bold  text-red-600 text-xs font-normal font-['Inter'] pr-[80%]">
              お知らせ
            </div>
            <div className="flex w-[259px] h-28 flex-col items-center p-4 space-y-2 bg-gray-100 rounded-[30px]">
              <div className="   text-black text-xl font-normal font-['Inter'] pb-5 pt-3">
                本日は閉館日です
              </div>
              <div className="text-black text-xs font-normal font-['Inter'] pl-10">
                X月X日
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
